# # # NUMpy 1 { Air bnb} NPS 

In [3]:
a=[1,2,3,True,"aditya","a"]
print(a)

[1, 2, 3, True, 'aditya', 'a']


In [4]:
# above we can see that list is accpeting all type of data 
#it look somthing somthing like {LIST} of python 

In [ ]:
"""NumPy is a library for the Python programming language, adding support for large, 
   multi-dimensional arrays and matrices,
  along with a large collection of high-level mathematical functions to operate on these arrays."""

In [5]:
# let installe the NUMpy first then we see exicution part 

In [2]:
!pip install numpy

In [5]:
import numpy as np

In [10]:
# here we use np as allias for numpy
np.abs(-6) 

6

In [21]:
b=[]
a=[1,2,3,4,5]
for i in range(len(a)):
    b.append(a[i]**2)
print(b)

[1, 4, 9, 16, 25]


In [18]:
# above is the example of how we execute in python get the squre of list element

In [ ]:
# NOW WE SEE HOW WE CAN GET SQUARE OF LIST WITH HELP OF NUMPY

In [20]:
#first we have to convert abpve list a in numpy array 
arr=np.array(a)
# IN SECODE PART WE JUST HAVE TO EXEDIRECTLY FROM
arr**2

array([ 1,  4,  9, 16, 25])

In [ ]:
# we can obserbe that we directly multiply the the whole array at once without use if loops 

In [34]:
lst=list(range(10000))
lst[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
#now we see how this pyhton list will time to execute
%timeit [i*i for i in lst ]

1.25 ms ± 164 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
# now we have got that how much time python list is taking to get execute IS = {1.25 MILI SECONDS ± 164 µs per loop}

In [41]:
arr2= np.array(lst)
print(arr2)

[   0    1    2 ... 9997 9998 9999]


In [42]:
%timeit (arr2)

67.2 ns ± 4.65 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [43]:
# now we have got that how much time NUMPY array is taking to get execute IS = {67.2 NANO SECONDS ± 4.65 ns per loop}

In [ ]:
#THIS MUCH NUMPY IS FASTER THAN THE PYTHON

# # # Dimention   &    Shapes

In [44]:
# let see with the example

In [47]:
arr=np.array(range(50))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

 TO SEE THE DIMENTION OF THIS ARRY WE HAVE TO USE ATTRIBUTE CALLE {ndim}

In [48]:
arr.ndim

1

In [ ]:
# this above ndim attribute show us that array arr is have one DIAMENTION......

In [49]:
arr.shape

(50,)

In [50]:
# it return the (50 ,) a tuple, which means we it is 1 dimention array

In [51]:
# THIS IS SOMETHING SOMTHING LIKE 2D LIST 

In [52]:
MAT = [[1,2,3],[4,5,6],[7,8,9]]
MAT1=np.array(MAT)
MAT1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
#NOW CHEQE THE DIMENTION {IT WILL SHOW US NUMBER OF DIMENTION WITH RESPECT TO AXIS}

In [54]:
MAT1.ndim

2

In [ ]:
# see it showing that this array is the 2 d array with respect to AXIS

In [56]:
# let cheak the shape
MAT1.shape
# it will show us dimention are there and how many element each dimeantion contains 

(3, 3)

# ndim represents the number of dimensions (axes) of the ndarray. shape is a tuple of integers representing the size of the ndarray in each dimensioN

# arrange { function }

In [57]:
# let see with the example 

In [62]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
# it is working just like range function of python, it take START AND STOP and return the list inside the tuple AND end is exluded

In [63]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [64]:
# here write the numpy code with some extra commenad in{ ARANGE }fucntion 
#above we  give start=1, stop=10, step= 2 just like list of python

In [66]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [68]:
# see our numpy function give us the array with float steps!!!!!!!!!!!!!!!!!!!!!!!!!!1
# all element are float value  beacuse numpy array are homogenuis in nature

In [69]:
# let see if we pass the array with  stirng and integer what will be the output    

In [70]:
np.array([1,2,3,"kola",0,4,4,7])

array(['1', '2', '3', 'kola', '0', '4', '4', '7'], dtype='<U11')

In [72]:
#AS YOU SEE ALL VALUE ARE GET CONVERTED INTO STRING 
#BEACASUE STRINGS are more in number than the INT values

# CONVERT THE DATA TYPE OF ARRAY  with dtype fucntion

In [73]:
#LET SEE WITH HELP OF EXAMPLE 

In [74]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

 this is how all interger are get converted into flaot with help of { dtype }function

# convert data type with help of  astype function 

In [76]:
#let see with the help of example 
ssr=np.array([1,2,4,5,6])
ssr

array([1, 2, 4, 5, 6])

In [78]:
#let convert the data type of array ssr 
ssr.astype('float')

array([1., 2., 4., 5., 6.])

In [ ]:
""" as you see the with help of astype function of numpy we convert all element of ssr array in float values """

# indexing and slicing

In [88]:
# let do with example
b1=np.arange(1,15,2)
b1

array([ 1,  3,  5,  7,  9, 11, 13])

In [89]:
b1[0] # here is we see that we ask numpy to give b1 of [0] index it give us the element of index 0 that is 1

1

In [90]:
b1[5] # here is we see that we numpy to give b1 of [5] index it give us the element of index 5 that is 11

11

In [91]:
b1[-1] # here is we see that we numpy to give b1 of [-1] index it give us the element of index -1 that is 13

13

# SLICING 

In [107]:
#LETS DO WITH AN EXAMPLE
c1=np.arange(20,40)
c1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [108]:
# now we make a slice of it
#reverse array
c1[::-1]

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20])

In [109]:
#with the jump
c1[::2]

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [111]:
#let make  it little complex
c1[-1:1:-3]

array([39, 36, 33, 30, 27, 24])

# size 

In [92]:
b1.size

7

In [93]:
# here is how we can get size of array

# sum

In [94]:
b1.sum()

49

In [95]:
# here is how we get sum of array b1

# how to get multiple index of array 

In [101]:
#lets see with help of example
d1=np.arange(1,20,3)
d1

array([ 1,  4,  7, 10, 13, 16, 19])

In [105]:
# and we want to see some value of an MULTIPLE INDEX
# LET DO IT 

d1[[2,4,3]]

array([ 7, 13, 10])

In [ ]:
""" AS WE CAN SEE, NUMPY GIVE US THE VALUES WHICH ARE PRESENT ON INDEX 2 ,  4  , 3 """

# BOOLEN INDEXING

In [115]:
#let do it with help of example 
bo=np.arange(4,20)
bo

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [117]:
# if we want see how the give us true and false ON THE BASIS OF CONDITION WE GIVE TO THEM 
bo>6 # HERE IS OUR CONDITION TO SEE WHAT IS TRUE AND WHAT IS NOT """

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [119]:
#if we want see which value are satisfy our condition we do this 

bo[[False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True]]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# """MASK"""

In [121]:
mask=bo>15
mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True])

In [57]:
#with the help of mask we can directly get the value which satisfy our condition
mask[bo]

NameError: name 'bo' is not defined

In [120]:
bo[bo<10]

array([4, 5, 6, 7, 8, 9])

In [126]:
#here we give the condition get get even number and numpy show us the values which are fullfill this condition
e=bo%2==0
bo[e]

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [127]:

#here we give the condition get get ODD number and numpy show us the values which are fullfill this condition
bo[bo%2!=0]



array([ 5,  7,  9, 11, 13, 15, 17, 19])

# NPS {USE CASE}

In [21]:
# this data is in float data type we know that ratings are not in float so we can change the data type of this data
#with help dtype and astype functions
scores = np.loadtxt('survey.txt')
scores

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [20]:
#astype function
scores.astype('int')

array([ 7, 10,  5, ...,  5,  9, 10])

In [22]:
#dtype function
scores = np.loadtxt('survey.txt',dtype='int')
scores

array([ 7, 10,  5, ...,  5,  9, 10])

In [41]:
total=scores.size
total

1167

In [25]:
# NOW WE HAVE SEE HOW MANY CUSTOMERS ARE GET PARTICIPETED FOR THIS SURVEY 
#HOW NUMPY CAN HELP US TO DO SO 
# AS YOU NUMPY HAVE THE ATTRIBUTE CALLED .SIZE WHICH WILL RETURNS THE SIZE OF ARRAY,
""" BY FINDING THE SIZE OF ARRAY WE CAN ANSWER HOW MANY PEOPLE GET PART IN THIS SURVEY"""

scores.size

1167

In [26]:
# this also the way we can find the part
scores.shape

(1167,)

In [34]:
#minimum of score
scores.min()

1

In [32]:
#naximum of scores
scores.max()

10

In [36]:
#how can we find the number of promoters from our survey 

In [37]:
# this is how find who are the promoters are but we have to number of this this we can do in seconde step 
scores[scores>8]

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [42]:
# is how we can get he number with help of size attribute
promoters =scores[scores>8].size
promoters

609

In [ ]:
# HOW TO FIND THE PERCENTAGE OF PROMOTERS

In [44]:
promoters_percentage = promoters/total*100
promoters_percentage

52.185089974293064

In [50]:
#HOW TO FIND THE DETRACTORS
DETRACTORS=scores[scores<7].size
DETRACTORS

332

In [ ]:
"""HOW TO FIND DETRACTORS PERCENTAGE"""

In [51]:
DETRACTORS_PERCENTAGE=DETRACTORS/total*100
DETRACTORS_PERCENTAGE

28.449014567266495

In [48]:
#THIS IS HOW WE CAN FIND THE DETRACTORS PERCENTAGE


# NOW WE CAN FIND THE NPS FOR Airbnb 

In [53]:
NPS = promoters_percentage - DETRACTORS_PERCENTAGE
NPS

23.73607540702657

In [54]:
#let make it round by 
round(NPS,2)

23.74